### ISSUE TITLE
pdb

### ISSUE THREAD

**Issue by shivan-s** [ericsia/vscode-python-snippet-pack-2.0#17]
Sorry to be extremely needy.

Can we get a snippet for adding `pdb`?

```
pdb -> __import__('pdb').set_trace()
```

Would this be useful?

**Comment by ericsia** [comment]
> Sorry to be extremely needy.
> 
> Can we get a snippet for adding `pdb`?
> 
> ```
> pdb -> __import__('pdb').set_trace()
> ```
> 
> Would this be useful?

No worry, good request always welcomed. Can you provide a link for the example how to use it? Or maybe even help to show me how to use it. Because I might as well add an example if necessary.

I tried to google but I didn't see example how to use it. Is it for adding breakpoint? VsCode is capable of adding breakpoint in python directly thought, in left side of line number click the red dot

**Comment by shivan-s** [comment]
Ahh, I see VSCode has this already built-in. I didn't realise. That's exactly right, it adds a breakpoint.

Can we keep this open? And see if anyone is interested, please.

Thanks in advance.

**Comment by ericsia** [comment]
> Ahh, I see VSCode has this already built-in. I didn't realise. That's exactly right, it adds a breakpoint.
> 
> Can we keep this open? And see if anyone is interested, please.
> 
> Thanks in advance.

But it will be bad for this extension reputation thought 😅 because from marketplace it will display this extension got 1 open issue. Plus I think not a lot of people will visit the github unless they notice a new bug by themself or came out a new suggestion.

Anyway, if you want this feature, do provide some python example I can add it to next update~
