### ISSUE TITLE
How do I deal with autocomplete adding two "." periods for methods?

### ISSUE THREAD

**Issue by lundeen-bryan** [ericsia/vscode-python-snippet-pack-2.0#24]
When I have a string value like s=input('Enter input')
Then on the next line I use output=s.  (then I start to type "isalnu"... then it correctly finds the isalnumeric method, but adds two periods so I am seeing 
s..isalnumeric

but I expect to see
s.isalnumeric

How do I make it add only one period?

**Comment by ericsia** [comment]
> isalnumeric

vscode update broke snippets function, the dot issue was there since last time
anyway, for me I can't even see the snippets suggestion, the intellisese hidden it:
![image](https://github.com/ericsia/vscode-python-snippet-pack-2.0/assets/24624808/8fca12fd-54c1-42d2-bc37-d239115fac0e)

use microsoft one will solve this problem i guess

**Comment by lundeen-bryan** [comment]
What do you mean by "use microsoft one will solve this problem..."? 
Was this a bug you can fix or are you saying it's a bug with VSCode from Microsoft?

**Comment by ericsia** [comment]
> What do you mean by "use microsoft one will solve this problem..."? Was this a bug you can fix or are you saying it's a bug with VSCode from Microsoft?

Install microsoft python pack, they included their own intellisense. Which will hide the repeated method of same name provided by this snippet, that will solve your problem @lundeen-bryan
